In [7]:
from google.colab import drive
drive.mount('/content/mount')

Drive already mounted at /content/mount; to attempt to forcibly remount, call drive.mount("/content/mount", force_remount=True).


In [8]:
%cd '/content/mount/MyDrive/SDS/'

/content/mount/MyDrive/SDS


In [9]:
!pip install -q libpysal
!pip install -q geopandas

In [10]:
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

import libpysal as ps  # サンプルデータセット"georgia"をインポートするために必要なモジュール

from Functions.gwr import GWR
from Functions.sel_bw import Sel_BW
from Functions.utils import *

In [11]:
# サンプルデータ"georgia"をインポートしてgeopandasデータフレームを作成
georgia = gpd.read_file(ps.examples.get_path('G_utm.shp'))

In [12]:
y, X, coords = get_input_data(georgia['PctBach'], georgia[['PctFB', 'PctBlack', 'PctRural']], georgia[['X', 'Y']], std=False)

In [13]:
selector = Sel_BW(y, X, coords)

In [14]:
bw = selector.search()
print(bw)

In [16]:
model = GWR(y, X, coords, bw)

In [19]:
model.fit()
print(model.beta_hat)

[[ 1.42207112e+01  1.05161773e+00  1.86733405e-02 -8.96608781e-02]
 [ 1.37287961e+01  7.60885754e-01  3.11904037e-02 -8.66691034e-02]
 [ 1.41084241e+01  9.43150004e-01  2.33396774e-02 -8.95014780e-02]
 [ 1.36867700e+01  7.03891785e-01  1.67276369e-02 -7.55529277e-02]
 [ 1.33699603e+01  3.30070586e+00 -5.54557885e-02 -5.06474756e-02]
 [ 1.33001359e+01  3.32578924e+00 -2.75323495e-02 -6.31813339e-02]
 [ 1.33525551e+01  3.30449013e+00 -3.02309537e-02 -6.22967519e-02]
 [ 1.22995105e+01  3.29870622e+00 -1.60421696e-02 -5.61929036e-02]
 [ 1.29596674e+01  9.66573587e-01  3.14180159e-02 -7.83038844e-02]
 [ 1.34442390e+01  7.01749069e-01  3.24036210e-02 -8.27645699e-02]
 [ 1.40756918e+01  2.75985082e+00 -5.27744842e-02 -5.57718355e-02]
 [ 1.33380775e+01  1.91683977e+00 -9.42739330e-03 -6.67526303e-02]
 [ 1.46942944e+01  8.40464368e-01  2.08953662e-02 -9.49100274e-02]
 [ 1.34754363e+01  5.84003477e-01  3.26673165e-02 -8.20149992e-02]
 [ 1.51706311e+01  1.27238751e+00 -1.91678297e-03 -9.31209926e

In [20]:
# 推定結果の表示
print(model.summary())

Geographically Weighted Regression (GWR) Results
Spatial kernel:                                           Adaptive bisquare
Bandwidth used:                                                         117
---------------------------------------------------------------------------
Number of observations:                                                 159
Number of covariates:                                                     4
Residual Sum of Squares:                                           1650.860
Effective number of parameters (trace(S)):                           11.805
Degree of freedom (n - trace(S)):                                   147.195
Sigma estimate:                                                       3.349
Maximum Log-likelihood:                                            -411.653
AIC:                                                                848.915
AICc:                                                               851.350
BIC:                                   