In [1]:
print('Hello World!')

Hello World!


In [2]:
a = 3
b = 5

In [3]:
c = a + b
print(c)

8


In [4]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a)
b = np.array([[3, 4, 5], [4, 5, 6]])
print(b)

[[1 2 3]
 [2 3 4]]
[[3 4 5]
 [4 5 6]]


In [6]:
c = a + b
print(c)

[[ 4  6  8]
 [ 6  8 10]]


In [7]:
c = a * b
print(c)

[[ 3  8 15]
 [ 8 15 24]]
